name: Get semantic release version

on:
  workflow_call:
    outputs:
      new_release_published:
        description: "Whether a new release was published. The return value is in the form of a string. ('true' or 'false')"
        value: ${{ jobs.get_version.outputs.new_release_published }}
      new_release_version:
        description: "Version of the new release. (e.g. '1.3.0')"
        value: ${{ jobs.get_version.outputs.new_release_version }}

jobs:
  get_version:
    runs-on: ubuntu-latest
    name: Update Version
    outputs:
      new_release_published : ${{ steps.semantic.outputs.new_release_published }}
      new_release_version  : ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
