name: Setup dotnet and build solution
description: Specific steps to build for Windows
inputs:
  dotnet_version:
    description: "Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x, 3.x, 6.0.2xx"
    required: false
  project_path:
    description: "The path to the executable project"
    required: true
  dotnet_build_args:
    description: "The arguments to be passed to the build command"
    required: false
    default: ''
  release_version:
    description: "The version of the app to be passed to the build commands"
    required: true
  dotnet_publish_args:
    description: "The arguments to be passed to the dotnet publish"
    required: false
    default: ''
  artifact_directory:
    description: "A path to a directory which is not used by the repository and can be action"
    required: false
    default: './publish-exe'
  file_name:
    description: "The resulting file name"
    required: false
    default: 'App'
outputs:
  cache_key:
    description: "The key of the cache storing the exe"
    value: ${{ steps.set_key.outputs.cache_key }}

runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - name: Build project
      run: dotnet build ${{ inputs.project_path }} `
        -c Release `
        /p:Version=${{ inputs.release_version }} `
        ${{ inputs.dotnet_build_args }}
      shell: pwsh

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Publish project
      run: dotnet publish ${{ inputs.project_path }} --no-build ${{ inputs.dotnet_publish_args }}
      shell: pwsh

    - name: Move and rename
      run: |
        $projectBaseDirectory = Split-Path ${{ inputs.project_path }}
        mkdir ${{ inputs.artifact_directory }}
        echo "Starting to copy files from $projectBaseDirectory/bin/Release/**/publish/*.exe"
        Get-ChildItem -Path "$projectBaseDirectory/bin/Release" -Recurse -Filter "*.exe" | Where-Object { $_.FullName -like "*\publish\*.exe" } | ForEach-Object {
          echo "Found $($_.FullName)"
          mv $_.FullName ${{ inputs.artifact_directory }}
        }
        echo "Starting to copy files from $projectBaseDirectory/bin/Release/**/publish/*.dll"
        Get-ChildItem -Path "$projectBaseDirectory/bin/Release" -Recurse -Filter "*.dll" | Where-Object { $_.FullName -like "*\publish\*.dll" } | ForEach-Object {
          echo "Found $($_.FullName)"
          mv $_.FullName ${{ inputs.artifact_directory }}
        }
        dir ${{ inputs.artifact_directory }}
        $zipPath = "${{ inputs.artifact_directory }}/${{ inputs.file_name }}.zip"
        Compress-Archive -Path "${{ inputs.artifact_directory }}/*" -DestinationPath $zipPath

        # Remove original files after successful compression
        Get-ChildItem -Path ${{ inputs.artifact_directory }} | Where-Object { $_.FullName -ne $zipPath } | Remove-Item -Recurse -Force
        dir ${{ inputs.artifact_directory }}
      shell: pwsh

    - name: Set cache_key
      id: set_key
      run: |
        echo "cache_key=publish-msix-${{ github.sha }}" >> $Env:GITHUB_OUTPUT
      shell: pwsh

    - name: Cache releases
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.artifact_directory }}
        key: ${{ steps.set_key.outputs.cache_key }}
        enableCrossOsArchive: true
