name: Setup dotnet and build solution
description: Specific steps to build for Windows
inputs:
  dotnet_version:
    description: "Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x, 3.x, 6.0.2xx"
    required: false
  project_path:
    description: "The path to the executable project. Should match the path in the '.wapproj'"
    required: true
  installer_project_path:
    description: "The path to the '.wapproj'"
    required: true
  dotnet_build_args:
    description: "The arguments to be passed to the build command"
    required: false
    default: ''
  release_version:
    description: "The version of the app to be passed to the build commands"
    required: true
  msix_platform:
    description: "The platform identifier of the .msix to be used. E.g. 'x64'"
    required: true
  dotnet_publish_args:
    description: "The arguments to be passed to the msbuild command when publishing the msix"
    required: false
    default: ''
  artifact_directory:
    description: "A path to a directory which is not used by the repository and can be action"
    required: false
    default: './publish-msix'
  file_name:
    description: "The resulting file name"
    required: false
    default: 'App'
outputs:
  cache_key:
    description: "The key of the cache storing the msix"
    value: ${{ steps.set_key.outputs.cache_key }}

runs:
  using: "composite"
  steps:
    - name: Replace project version in Package.appxmanifest
      run: |
        $projectBaseDirectory = Split-Path ${{ inputs.installer_project_path }}
        $manifestPath = "$projectBaseDirectory/Package.appxmanifest"
        echo "Updating version of manifest $manifestPath to ${{ inputs.release_version }}"
        (Get-Content $manifestPath) -replace ' Version="([0-9]+\.[0-9]+\.[0-9]+)\.0"', " Version=`"${{ inputs.release_version }}.0`"" | Set-Content $manifestPath
      shell: pwsh

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - name: Build project
      run: dotnet build -c Release `
        /p:RuntimeIdentifiers=win-${{ inputs.msix_platform }} `
        /p:Version=${{ inputs.release_version }} `
        ${{ inputs.dotnet_build_args }}
      shell: pwsh

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Create the app package
      run: |
        msbuild ${{ inputs.installer_project_path}} `
            /restore /t:Rebuild `
            /p:Configuration=Release `
            /p:Platform=${{ inputs.msix_platform }} `
            /p:UapAppxPackageBuildMode=SideloadOnly `
            /p:AppxBundle=Never `
            /p:GenerateAppxPackageOnBuild=true `
            /p:AppxPackageSigningEnabled=false `
            /p:Version=${{ inputs.release_version }} ${{ inputs.dotnet_publish_args }}
      shell: pwsh

    - name: Move and rename
      run: |
        $projectBaseDirectory = Split-Path ${{ inputs.installer_project_path }}
        mkdir ${{ inputs.artifact_directory }}
        echo "Starting to copy files from $projectBaseDirectory\AppPackages"
        dir $projectBaseDirectory\AppPackages
        Get-ChildItem -Path $projectBaseDirectory\AppPackages -Recurse -Filter *.msix* | ForEach-Object {
          echo "Found $($_.FullName)"
          mv $_.FullName ${{ inputs.artifact_directory }}
        }
        dir ${{ inputs.artifact_directory }}
        $file = Get-Item "${{ inputs.artifact_directory }}\*.Installer_*.msix"
        if ($file.FullName -eq $null) {
          throw "No file found"
        }
        Rename-Item -Path $file.FullName -NewName "${{ inputs.file_name }}.msix"
        dir ${{ inputs.artifact_directory }}
      shell: pwsh

    - name: Set cache_key
      id: set_key
      run: |
        echo "cache_key=publish-msix-${{ github.sha }}" >> $Env:GITHUB_OUTPUT
      shell: pwsh

    - name: Cache releases
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.artifact_directory }}
        key: ${{ steps.set_key.outputs.cache_key }}
        enableCrossOsArchive: true
